# include 3rdparty
MACRO(LOAD_LIB3RDPARTY cur_os cur_arch)
    SET(3RDPARTY_DIR ${CMAKE_SOURCE_DIR}/3rdparty/target/${${cur_os}}_${${cur_arch}})
    MESSAGE(STATUS "3RDPARTY_DIR: ${3RDPARTY_DIR}")

    FIND_FILE(3RDPARTY_INCLUDE_DIR include ${3RDPARTY_DIR} NO_DEFAULT_PATH)
    FIND_FILE(3RDPARTY_LIBRARY_DIR lib ${3RDPARTY_DIR} NO_DEFAULT_PATH)
    MESSAGE(STATUS "3RDPARTY_INCLUDE_DIR: ${3RDPARTY_INCLUDE_DIR}")
    MESSAGE(STATUS "3RDPARTY_LIBRARY_DIR: ${3RDPARTY_LIBRARY_DIR}")

ENDMACRO()
