IF(CMAKE_VERSION VERSION_LESS "3.1")
    IF(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11")
    ENDIF()
ELSE()
    SET(CMAKE_CXX_STANDARD 11)
ENDIF()


IF (NOT CMAKE_CXX_STANDARD)
    SET(CMAKE_CXX_STANDARD 11)
    SET(CMAKE_CXX_STANDARD_REQUIRED ON)
ENDIF()

SET(CMAKE_CXX_EXTENSIONS  OFF)

IF(CMAKE_SYSTEM_NAME MATCHES "CYGWIN")
	SET(CMAKE_CXX_EXTENSIONS ON)
ENDIF()