// the configured optins and setting for version
#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 1
#define PROJECT_VERSION_PATCH 0

#define PLOG_VERSION_MAJOR 0
#define PLOG_VERSION_MINOR 1
#define PLOG_VERSION_PATCH 0

#define UTILS_VERSION_MAJOR 0
#define UTILS_VERSION_MINOR 1
#define UTILS_VERSION_PATCH 0
